import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#636262",
        "error-container": "#ffdad6",
        "on-surface": "#1a1c19",
        "on-surface-variant": "#454933",
        "surface-container-highest": "#e2e3de",
        "inverse-on-surface": "#f1f1ec",
        "primary-fixed-dim": "#b8d300",
        "secondary-fixed-dim": "#c8c6c5",
        "surface-bright": "#fafaf5",
        secondary: "#5f5e5e",
        "surface-container": "#eeeee9",
        "on-secondary-fixed": "#1b1c1c",
        "on-primary-fixed-variant": "#414c00",
        surface: "#fafaf5",
        outline: "#767960",
        "tertiary-fixed-dim": "#b1c5ff",
        "surface-container-high": "#e8e8e4",
        "on-background": "#1a1c19",
        background: "#fafaf5",
        "tertiary-container": "#d9e1ff",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#e5e2e1",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#dae2ff",
        "primary-container": "#d2f000",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#001946",
        primary: "#576500",
        "surface-dim": "#dadad6",
        "on-tertiary-fixed-variant": "#00419e",
        "on-primary-container": "#5c6b00",
        "on-tertiary-container": "#2c5fc3",
        "on-secondary-fixed-variant": "#474746",
        "secondary-container": "#e2dfde",
        "on-primary-fixed": "#191e00",
        "outline-variant": "#c6c9ac",
        tertiary: "#2559bd",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f4f4ef",
        "surface-variant": "#e2e3de",
        "inverse-primary": "#b8d300",
        "on-primary": "#ffffff",
        "surface-tint": "#576500",
        "inverse-surface": "#2f312e",
        "primary-fixed": "#d2f001",
      },
      fontFamily: {
        headline: ["var(--font-headline)", "sans-serif"],
        handwritten: ["var(--font-handwritten)", "cursive"],
        body: ["var(--font-body)", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
